#!/usr/bin/env python

import argparse
from capstone import *
import mmap
from sortedcontainers import SortedDict
import subprocess as sp

# local import
from bcolors import colors

# commands
parser = argparse.ArgumentParser()
parser.add_argument('--arch', '-m', action='store', default='armv8', choices=['armv7', 'thumbv7', 'armv8'],
                    help='instructions for arm: armv7, thumbv7 or armv8')
parser.add_argument('--verbose', '-v', action='store_true', default=False, help='print commands')
parser.add_argument('binary', nargs=2, help='binaries to compare')
args = parser.parse_args()


md = Cs(CS_ARCH_ARM64, CS_MODE_ARM)
f1 = open(args.binary[0], 'rb')
binary1 = mmap.mmap(f1.fileno(), length=0, access=mmap.ACCESS_READ)
f1.close()
f2 = open(args.binary[1], 'rb')
binary2 = mmap.mmap(f2.fileno(), length=0, access=mmap.ACCESS_READ)
f2.close()
print(f'compare result: {binary1==binary2}')
diff = SortedDict()
x = 0
for i, (first, second) in enumerate(zip(binary1, binary2)):
    if first != second:
        diff[i] = [first.hex(), second.hex()]


sequences1 = {}
sequences2 = {}
shift, strings = diff.popitem(0)
start = shift
print(f'shift: {shift}, strings: {strings}')
while diff:
    next_address, _bytes = diff.popitem(0)
    if int(next_address) - int(shift) < 2:
        strings[0] += _bytes[0]
        strings[1] += _bytes[1]
    else:
        sequences1[shift] = ' '.join(strings[0].split())
        sequences2[shift] = ' '.join(strings[1].split())
        strings[0] = _bytes[0]
        strings[1] = _bytes[1]
        shift = next_address


def print_colored(string, color=None):
    if color:
        print(color + string + colors.ENDC)
    else:
        print(string)


def print_instruction(text, address, align, color):
    lines = text.split('\n')
    _next_address = address
    next_address_string = '0x%08x' % _next_address
    for line in lines:
        string = ' '.join(line.split())
        if 'text' not in string and string != '':
            instruction = next_address_string + ':\t' + string
            print_colored(instruction, color)
            _next_address += align
            next_address_string = '0x%08x' % _next_address


def process_opcode(opcode, address):
    strings = []
    for instr in md.disasm(opcode, address):
        print("0x%x:\t%s\t%s" % (instr.address, instr.mnemonic, instr.op_str))


def convert_opcode(opcode, address, arch='armv8', color=None):
    _out = process_opcode(opcode, address)
    _step = 2 if arch == 'thumbv7' else 4
    if _out:
        print_instruction(_out, address, _step, color)
    elif arch == 'thumbv7':
        convert_opcode(opcode, address, 'armv8', color)
    else:
        address_string = '0x%08x' % address + f':\t{opcode}'
        print_colored(address_string, color)


def read_bytes(address, length, binary):
    """Read bytes from the binary

    :param address: Start address in the binary
    :param length: Number of bytes to read
    :param binary: Binary file
    :returns: bytearray
    """
    start = address
    end = start + length + 1
    return binary[start:end]


delimiter = '------------------------------------------------------------'
print(delimiter)
step = 2 if args.arch == 'thumbv7' else 4
# Print opcode diffs
for shift in sequences1:
    opcode1 = sequences1[shift]
    opcode2 = sequences2[shift]
    print('Opcode1: ' + opcode1)
    print('Opcode2: ' + opcode2)
    print('Address: 0x%08x' % int(shift))
    address_before = (int(shift) & ~3) - (4 if args.arch == 'thumbv7' else 8)

    print('ARM instruction set: ' + args.arch)
    length = 0 if len(opcode1.split(' ')) < step else len(opcode1.split(' '))
    address_after = (int(shift) & ~1) + length
    out = read_bytes(address_before, step * 2, binary1)
    convert_opcode(out, address_before, args.arch)

    if length == 0:
        out = read_bytes(address_after, step, binary1)
        convert_opcode(out, address_after, args.arch, colors.RED)
        out = read_bytes(address_after, step, binary2)
        convert_opcode(out, address_after, args.arch, colors.GREEN)
        address_after = address_after + step
    else:
        if shift & 1:
            out = read_bytes(shift & ~1, step, binary1)
            convert_opcode(out, shift & ~1, args.arch, colors.RED)
            out = read_bytes(shift & ~1, step, binary2)
            convert_opcode(out, shift & ~1, args.arch, colors.GREEN)
        else:
            convert_opcode(opcode1, shift, args.arch, colors.RED)
            convert_opcode(opcode2, shift, args.arch, colors.GREEN)

    out = read_bytes(address_after, step * 2, binary1)
    convert_opcode(out, address_after, args.arch)
    print(delimiter)
